import { hover } from "@testing-library/user-event/dist/hover"
import { config } from "./common/config"

export const primaryColor = config.env === "dev" ? '#7db788ff' : '#09a498'

// Theme colors specific to light theme
const themecolor = {
  direction: 'ltr',
  name: 'light',
  token: {
    authbgcolor: 'rgb(239,242,247)',
    colorTextDescription: '#878a99',
    //color
    colorSuccessBg: '#ecfff3',
    colorInfoBg: '#dbeff3',
    colorWarningBg: '#fffbe6',
    colorDangerBg: '#fff1f0',
    colorYellowBg: '#fffbe6',
    colorGrayrBg: '#f6f7f8',
    colorPurpleBg: '#e7dffe',
    colorRedBg: '#fff0f0',
    colorLightBlue: '#ecf3ff',
    //text
    textMute: '#878a99',
    sidebarText: '#333232',
    textInfo: '#4ab0c1',
    textDark: '#000',
    textLight: '#000',
    contactBg: '#d9e8ff',
    textBlue: '#438eff',
    borderGray: ' #ebebeb',
    colorPrimary: primaryColor,
    colorPrimaryBg: '#f0f0f0',
    colorSplit: 'rgba(5, 5, 5, 0.06)',
    colorFillTertiary: 'rgba(0, 0, 0, 0.04)',
    emailText: '#747373',
    emailSubText: '#000',
    emailSidebar: 'rgba(150, 150, 150, 0.08)',
    emailSidebars: 'rgba(150, 150, 150, 0.08)',
    colorBorder: '#D0D5DD',
    colorBgContainer: '#fff',
    //tooltips Data Display
    colorBgSpotlight: 'rgba(0, 0, 0, 0.85)', // tooltip bg color
    colorTextLightSolid: '#fff', // tooltip color
    //Drawer Feedback
    colorBgElevated: '#fff', //Drawer bg color
    colorBgMask: 'rgba(0, 0, 0, 0.45)', //Drawer overlay bg
    colorIcon: 'rgba(0, 0, 0, 0.45)', //Drawer close button color
    colorIconHover: 'rgba(0, 0, 0, 0.88)', //Drawer close hover button color
    colorTextTertiary: 'rgba(0, 0, 0, 0.45)',
    colorTextSecondary: '#000',
    colorTextLabel: 'rgba(0, 0, 0, 0.65)',
    colorText: '#000',

    //Spacing and sizes
    controlHeight: 35,
    controlHeightLG: 40,
    controlHeightSM: 24,
    controlOutlineWidth: 2,
    fontSizeIcon: 12,
    fontSize: 14,
    fontSizeHeading1: 38,
    fontSizeHeading2: 30,
    fontSizeHeading3: 24,
    fontSizeHeading4: 20,
    fontSizeHeading5: 16,
    fontSizeLG: 16,
    fontWeightStrong: 600,
    linkDecoration: 'none',
    linkHoverDecoration: 'none',
    lineType: 'solid',
    lineWidth: 1,
    lineWidthBold: 2,
    lineWidthFocus: 4,

    sizePopupArrow: 18,
    zIndexPopupBase: 1000,
    controlPaddingHorizontal: 12,
    controlPaddingHorizontalSM: 8,
    boxShadowTertiary:
      '0 1px 2px 0 rgba(0, 0, 0, 0.03), 0 1px 6px -1px rgba(0, 0, 0, 0.02), 0 2px 4px 0 rgba(0, 0, 0, 0.02)',
    boxShadowSecondary:
      '0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)',
    screenLGMax: 1199,
    screenMDMax: 991,
    screenSMMax: 767,
    screenXSMax: 575,
    gray: '#2b313e',
  },
  components: {
    Header: {
      background: '#ffffffff',
      color: '#000000ff',
      padding: '12px 16px',
    },
    Footer: `bg-[#ffffff] text-[#000000ff] py-[10px] px-[16px]`,
    Button: `text-[#fff] shadow hover:!bg-[#087f70] hover:!text-[#fff] hover:!font-[700] transition-all duration-600`,
    Form: {
      labelMarginBottom: '0.5rem',
      marginLG: '1rem',
    },
    Menu: {
      headerBgColor: '#fff',
      verticalSidebarWidth: 200,
      groupTitleColor: '#000000',
      itemBg: '#fff',
      itemColor: '#000000',
      itemActiveBg: '#EEF2FF',
      itemHoverBg: '#EEF2FF',
      itemHoverColor: primaryColor,
      subMenuItemBg: '#ffffff',
      itemSelectedBg: '#EEF2FF',
      menuBorderColor: '#eff2f7',
    },
    Typography: ``,
    Text: `text-[#000000] font-[15px] leading-[1.5] mx-[70px]`,
    //navigation
    Anchor: {
      linkPaddingBlock: 4,
      linkPaddingInlineStart: 16,
    },
    Breadcrumb: {
      iconFontSize: 15,
      itemColor: '#adb5bd',
      lastItemColor: '#2b313e',
      linkColor: '#2b313e',
      linkHoverColor: '#2b313e',
      separatorColor: '#adb5bd',
      separatorMargin: 8,
    },
    Pagination: {
      itemActiveBg: '#ffffff',
      itemActiveBgDisabled: 'rgba(0, 0, 0, 0.15)',
      itemActiveColorDisabled: 'rgba(0, 0, 0, 0.25)',
      itemBg: '#ffffff',
      itemInputBg: '#ffffff',
      itemLinkBg: '#ffffff',
      itemSize: 32,
      itemSizeSM: 24,
    },
    Steps: {
      customIconFontSize: 24,
      customIconSize: 32,
      customIconTop: 0,
      descriptionMaxWidth: 140,
      dotCurrentSize: 10,
      dotSize: 8,
      iconFontSize: 14,
      iconSize: 32,
      iconSizeSM: 24,
      iconTop: -0.5,
      navArrowColor: 'rgba(0, 0, 0, 0.25)',
      navContentMaxWidth: 'auto',
      titleLineHeight: 32,
    },
    //Data Entry
    AutoComplete: {
      zIndexPopup: 1050,
    },
    Cascader: {
      controlItemWidth: 111,
      controlWidth: 184,
      dropdownHeight: 180,
    },
    DatePicker: {
      presetsMaxWidth: 200,
      presetsWidth: 120,
      zIndexPopup: 1050,
    },
    InputNumber: {
      controlWidth: 90,
      handleFontSize: 7,
      handleVisible: 'auto',
      handleWidth: 22,
    },
    Mentions: {
      controlItemWidth: 100,
      dropdownHeight: 250,
      zIndexPopup: 1050,
    },
    Radio: {
      buttonBg: '#ffffff',
      buttonCheckedBg: '#ffffff',
      buttonCheckedBgDisabled: 'rgba(0, 0, 0, 0.1)',
      buttonCheckedColorDisabled: 'rgba(0, 0, 0, 0.50)',
      buttonColor: 'rgba(0, 0, 0, 0.88)',
      buttonPaddingInline: 15,
      buttonSolidCheckedColor: '#fff',
      dotColorDisabled: 'rgba(0, 0, 0, 0.25)',
      dotSize: 8,
      radioSize: 16,
      wrapperMarginInlineEnd: 8,
    },
    Select: {
      zIndexPopup: 1050,
    },
    Slider: {
      controlSize: 20,
      dotSize: 8,
      handleLineWidth: 2,
      handleLineWidthHover: 4,
      handleSize: 10,
      handleSizeHover: 12,
      railSize: 4,
    },
    TimePicker: {
      presetsMaxWidth: 200,
      presetsWidth: 120,
      zIndexPopup: 1050,
    },
    Transfer: {
      headerHeight: 40,
      itemHeight: 32,
      itemPaddingBlock: 8,
      listHeight: 200,
      listWidth: 180,
      listWidthLG: 250,
    },
    //Data Display
    Avatar: {
      groupBorderColor: '#ffffff',
    },
    Calendar: {
      fullBg: '#ffffff',
      fullPanelBg: '#ffffff',
      miniContentHeight: 256,
      monthControlWidth: 80,
      yearControlWidth: 90,
    },
    Card: `bg-[#ffffff] shadow-md hover:shadow-lg transition-shadow duration-300`,
    Carousel: {
      dotActiveWidth: 24,
      dotHeight: 3,
      dotWidth: 16,
    },
    Descriptions: {
      colonMarginLeft: 2,
      colonMarginRight: 8,
      extraColor: 'rgba(0, 0, 0, 0.88)',
      itemPaddingBottom: 16,
      labelBg: 'rgba(0, 0, 0, 0.02)',
      titleMarginBottom: 20,
    },
    List: {
      avatarMarginRight: 14,
      contentWidth: 220,
      descriptionFontSize: 14,
      emptyTextPadding: 16,
      footerBg: 'transparent',
      headerBg: 'transparent',
      itemPadding: '12px 0',
      itemPaddingLG: '16px 24px',
      itemPaddingSM: '8px 16px',
      metaMarginBottom: 16,
      titleMarginBottom: 10,
    },
    Popover: {
      // minWidth:                                    177,
      // width:                                       177,
      zIndexPopup: 1030,
    },
    Segmented: {
      itemActiveBg: 'rgba(0, 0, 0, 0.15)',
      itemColor: '#878a99',
      itemHoverBg: 'rgba(0, 0, 0, 0.02)',
      itemHoverColor: '#141821',
      itemSelectedBg: '#ffffff',
    },
    Statistic: {
      contentFontSize: 22,
      titleFontSize: 15,
    },
    Tabs: {
      cardBg: '#f5f5f5',
      cardGutter: 4,
      cardHeight: 40,
      cardPadding: '8px 16px',
      cardPaddingLG: '8px 16px 6px',
      cardPaddingSM: '6px 16px',
      horizontalItemGutter: 25,
      horizontalItemPadding: '12px 0',
      horizontalItemPaddingLG: '16px 0',
      horizontalItemPaddingSM: '8px 0',
      horizontalMargin: '0 0 16px 0',
      titleFontSize: 15,
      titleFontSizeLG: 16,
      titleFontSizeSM: 14,
      verticalItemMargin: '16px 0 0 0',
      zIndexPopup: 1050,
    },
    Tag: {
      defaultBg: '#EEF2FF',
      defaultColor: '#000000',
    },
    Timeline: {
      itemPaddingBottom: 12,
      dotBorderWidth: 2,
      tailColor: '#eff2f7',
      tailWidth: 2,
    },
    Tooltip: {
      zIndexPopup: 1070,
    },
    Tree: {
      headerHeight: 40,
      itemHeight: 180,
      itemPaddingBlock: 5,
      listHeight: 200,
      listWidth: 180,
      listWidthLG: 250,
    },
    //Feedback
    Drawer: {
      footerPaddingBlock: 8,
      footerPaddingInline: 16,
      zIndexPopup: 1000,
    },
    Message: {
      contentBg: '#ffffff',
      contentPadding: '10px 16px',
      zIndexPopup: '1010',
    },
    Modal: {
      contentBg: '#ffffff',
      footerBg: '#ffffff',
      headerBg: '#ffffff',
      titleColor: 'rgba(0, 0, 0, 0.88)',
      titleFontSize: 16,
      titleLineHeight: 1.5,
    },
    Notification: {
      width: 384,
      zIndexPopup: 1050,
    },
    Popconfirm: {
      zIndexPopup: 1060,
    },
    Result: {
      extraMargin: '24px 0 0 0', //result-extra margin
      iconFontSize: 55,
      subtitleFontSize: 15,
      titleFontSize: 24,
    },
    Spin: {
      contentHeight: 400,
    },
    // Layout: {
    //     colorBgBody: '#fff',
    //     colorBgHeader: '#fff',
    //     colorBgTrigger: '#002140',
    // },
  },
}

// Theme colors specific to dark theme
const darkthemecolors = {
  direction: 'ltr',
  name: 'dark',
  token: {
    authbgcolor: '#19202a',
    colorTextDescription: '#9da5b5',
    //color
    colorSuccessBg: '#1f3e37',
    colorInfoBg: '#1d414a',
    colorWarningBg: '#4a4128',
    colorDangerBg: '#4a3031',
    colorYellowBg: '#4a4128',
    colorGrayrBg: '#2a2f37',
    colorPurpleBg: '#352e42',
    colorRedBg: '#4a3031',
    colorLightBlue: '#1d3e5a',
    //text
    textMute: '#9da5b5',
    sidebarText: '#e8e8e8',
    textInfo: '#4ab0c1',
    textDark: '#fff',
    textLight: '#fff',
    contactBg: '#2a3b5a',
    textBlue: '#438eff',
    borderGray: '#3e4453',
    colorPrimary: primaryColor,
    colorPrimaryBg: '#2a2f37',
    colorSplit: 'rgba(255, 255, 255, 0.1)',
    colorFillTertiary: 'rgba(255, 255, 255, 0.08)',
    emailText: '#c9c9c9',
    emailSubText: '#fff',
    emailSidebar: 'rgba(200, 200, 200, 0.08)',
    emailSidebars: 'rgba(200, 200, 200, 0.08)',
    colorBorder: '#3e4453',
    colorBgContainer: '#202832',
    //tooltips Data Display
    colorBgSpotlight: 'rgba(255, 255, 255, 0.85)',
    colorTextLightSolid: '#ffffffff',
    //Drawer Feedback
    colorBgElevated: '#202832',
    colorBgMask: 'rgba(0, 0, 0, 0.65)',
    colorIcon: 'rgba(255, 255, 255, 0.45)',
    colorIconHover: 'rgba(255, 255, 255, 0.88)',
    colorTextTertiary: 'rgba(255, 255, 255, 1)',
    colorTextSecondary: '#fff',
    colorTextLabel: 'rgba(255, 255, 255, 0.65)',
    colorText: '#fff',

    // Spacing and sizes - These remain the same as they are not color-related
    controlHeight: 35,
    controlHeightLG: 40,
    controlHeightSM: 24,
    controlOutlineWidth: 2,
    fontSizeIcon: 12,
    fontSize: 14,
    fontSizeHeading1: 38,
    fontSizeHeading2: 30,
    fontSizeHeading3: 24,
    fontSizeHeading4: 20,
    fontSizeHeading5: 16,
    fontSizeLG: 16,
    fontWeightStrong: 600,
    linkDecoration: 'none',
    linkHoverDecoration: 'none',
    lineType: 'solid',
    lineWidth: 1,
    lineWidthBold: 2,
    lineWidthFocus: 4,
    sizePopupArrow: 18,
    zIndexPopupBase: 1000,
    controlPaddingHorizontal: 12,
    controlPaddingHorizontalSM: 8,
    boxShadowTertiary:
      '0 1px 2px 0 rgba(255, 255, 255, 0.03), 0 1px 6px -1px rgba(255, 255, 255, 0.02), 0 2px 4px 0 rgba(255, 255, 255, 0.02)',
    boxShadowSecondary:
      '0 6px 16px 0 rgba(255, 255, 255, 0.08), 0 3px 6px -4px rgba(255, 255, 255, 0.12), 0 9px 28px 8px rgba(255, 255, 255, 0.05)',
    screenLGMax: 1199,
    screenMDMax: 991,
    screenSMMax: 767,
    screenXSMax: 575,
    gray: '#f6f7f8',
  },
  components: {
    Header: {
      color: '#fff',
      padding: '12px 16px',
      background: '#2f2f2fff',
    },
    Footer: `bg-[#1b1b1b] text-[#fff] py-[10px] px-[16px]`,
    Button:  `text-[#fff] shadow hover:!bg-[#087f70] hover:!text-[#fff] hover:!font-[700] transition-all duration-600`,
    Form: {
      labelMarginBottom: '0.5rem',
      marginLG: '1rem',
    },
    Menu: {
      headerBgColor: '#2a2f37',
      verticalSidebarWidth: 200,
      groupTitleColor: '#fff',
      itemBg: '#2a2f37',
      itemColor: '#fff',
      itemActiveBg: '#333b49',
      itemHoverBg: '#333b49',
      itemHoverColor: primaryColor,
      subMenuItemBg: '#2a2f37',
      itemSelectedBg: '#333b49',
      menuBorderColor: '#2b313e',
    },
    Typography: {
      titleMarginBottom: '1rem',
      titleMarginTop: '0',
      color: '#fff',
    },
    Text: `text-[#ffffffff] font-[15px] leading-[1.5] mx-[70px]`,
    //navigation
    Anchor: {
      linkPaddingBlock: 4,
      linkPaddingInlineStart: 16,
    },
    Breadcrumb: {
      iconFontSize: 15,
      itemColor: '#7d8794',
      lastItemColor: '#d6dde6',
      linkColor: '#d6dde6',
      linkHoverColor: '#d6dde6',
      separatorColor: '#7d8794',
      separatorMargin: 8,
    },
    Pagination: {
      itemActiveBg: '#333b49',
      itemActiveBgDisabled: 'rgba(255, 255, 255, 0.15)',
      itemActiveColorDisabled: 'rgba(255, 255, 255, 0.25)',
      itemBg: '#2a2f37',
      itemInputBg: '#2a2f37',
      itemLinkBg: '#2a2f37',
      itemSize: 32,
      itemSizeSM: 24,
    },
    Steps: {
      customIconFontSize: 24,
      customIconSize: 32,
      customIconTop: 0,
      descriptionMaxWidth: 140,
      dotCurrentSize: 10,
      dotSize: 8,
      iconFontSize: 14,
      iconSize: 32,
      iconSizeSM: 24,
      iconTop: -0.5,
      navArrowColor: 'rgba(255, 255, 255, 0.25)',
      navContentMaxWidth: 'auto',
      titleLineHeight: 32,
    },
    //Data Entry
    AutoComplete: {
      zIndexPopup: 1050,
    },
    Cascader: {
      controlItemWidth: 111,
      controlWidth: 184,
      dropdownHeight: 180,
    },
    DatePicker: {
      presetsMaxWidth: 200,
      presetsWidth: 120,
      zIndexPopup: 1050,
    },
    InputNumber: {
      controlWidth: 90,
      handleFontSize: 7,
      handleVisible: 'auto',
      handleWidth: 22,
    },
    Mentions: {
      controlItemWidth: 100,
      dropdownHeight: 250,
      zIndexPopup: 1050,
    },
    Radio: {
      buttonBg: '#2a2f37',
      buttonCheckedBg: '#333b49',
      buttonCheckedBgDisabled: 'rgba(255, 255, 255, 0.1)',
      buttonCheckedColorDisabled: 'rgba(255, 255, 255, 0.50)',
      buttonColor: '#fff',
      buttonPaddingInline: 15,
      buttonSolidCheckedColor: '#141821',
      dotColorDisabled: 'rgba(255, 255, 255, 0.25)',
      dotSize: 8,
      radioSize: 16,
      wrapperMarginInlineEnd: 8,
    },
    Select: {
      zIndexPopup: 1050,
    },
    Slider: {
      controlSize: 20,
      dotSize: 8,
      handleLineWidth: 2,
      handleLineWidthHover: 4,
      handleSize: 10,
      handleSizeHover: 12,
      railSize: 4,
    },
    TimePicker: {
      presetsMaxWidth: 200,
      presetsWidth: 120,
      zIndexPopup: 1050,
    },
    Transfer: {
      headerHeight: 40,
      itemHeight: 32,
      itemPaddingBlock: 8,
      listHeight: 200,
      listWidth: 180,
      listWidthLG: 250,
    },
    //Data Display
    Avatar: {
      groupBorderColor: '#202832',
    },
    Calendar: {
      fullBg: '#2a2f37',
      fullPanelBg: '#2a2f37',
      miniContentHeight: 256,
      monthControlWidth: 80,
      yearControlWidth: 90,
    },
    Card: `bg-[#444444ff] shadow-md hover:shadow-lg transition-shadow duration-300`,
    Carousel: {
      dotActiveWidth: 24,
      dotHeight: 3,
      dotWidth: 16,
    },
    Descriptions: {
      colonMarginLeft: 2,
      colonMarginRight: 8,
      extraColor: '#fff',
      itemPaddingBottom: 16,
      labelBg: 'rgba(255, 255, 255, 0.05)',
      titleMarginBottom: 20,
    },
    List: {
      avatarMarginRight: 14,
      contentWidth: 220,
      descriptionFontSize: 14,
      emptyTextPadding: 16,
      footerBg: 'transparent',
      headerBg: 'transparent',
      itemPadding: '12px 0',
      itemPaddingLG: '16px 24px',
      itemPaddingSM: '8px 16px',
      metaMarginBottom: 16,
      titleMarginBottom: 10,
    },
    Popover: {
      zIndexPopup: 1030,
    },
    Segmented: {
      itemActiveBg: 'rgba(255, 255, 255, 0.15)',
      itemColor: '#9da5b5',
      itemHoverBg: 'rgba(255, 255, 255, 0.05)',
      itemHoverColor: '#fff',
      itemSelectedBg: '#333b49',
    },
    Statistic: {
      contentFontSize: 22,
      titleFontSize: 15,
    },
    Tabs: {
      cardBg: '#2a2f37',
      cardGutter: 4,
      cardHeight: 40,
      cardPadding: '8px 16px',
      cardPaddingLG: '8px 16px 6px',
      cardPaddingSM: '6px 16px',
      horizontalItemGutter: 25,
      horizontalItemPadding: '12px 0',
      horizontalItemPaddingLG: '16px 0',
      horizontalItemPaddingSM: '8px 0',
      horizontalMargin: '0 0 16px 0',
      titleFontSize: 15,
      titleFontSizeLG: 16,
      titleFontSizeSM: 14,
      verticalItemMargin: '16px 0 0 0',
      zIndexPopup: 1050,
    },
    Tag: {
      defaultBg: '#333b49',
      defaultColor: '#fff',
    },
    Timeline: {
      itemPaddingBottom: 12,
      dotBorderWidth: 2,
      tailColor: '#3e4453',
      tailWidth: 2,
    },
    Tooltip: {
      zIndexPopup: 1070,
    },
    Tree: {
      headerHeight: 40,
      itemHeight: 180,
      itemPaddingBlock: 5,
      listHeight: 200,
      listWidth: 180,
      listWidthLG: 250,
    },
    //Feedback
    Drawer: {
      footerPaddingBlock: 8,
      footerPaddingInline: 16,
      zIndexPopup: 1000,
    },
    Message: {
      contentBg: '#2a2f37',
      contentPadding: '10px 16px',
      zIndexPopup: '1010',
    },
    Modal: {
      contentBg: '#2a2f37',
      footerBg: '#2a2f37',
      headerBg: '#2a2f37',
      titleColor: '#fff',
      titleFontSize: 16,
      titleLineHeight: 1.5,
    },
    Notification: {
      width: 384,
      zIndexPopup: 1050,
    },
    Popconfirm: {
      zIndexPopup: 1060,
    },
    Result: {
      extraMargin: '24px 0 0 0',
      iconFontSize: 55,
      subtitleFontSize: 15,
      titleFontSize: 24,
    },
    Spin: {
      contentHeight: 400,
    },
  },
}

const getTheme = theme => (theme === 'dark' ? darkthemecolors : themecolor)

export { themecolor, darkthemecolors, getTheme }
